SELECT [media_set_id]
   ,[family_sequence_number]
   ,[media_family_id]
   ,[media_count]
   ,[logical_device_name]
   ,[physical_device_name]
   ,[device_type]
   ,[physical_block_size]
   ,[mirror]
 FROM [msdb].[dbo].[backupmediafamily]